openapi: 3.0.3
info:
  title: Enviate API - NOTIFICATION SERVICE
  description: |-
    Enviate offers a web application that streamlines the linkage between business/product needs and software development. By establishing an automated, bidirectional connection between requirements and software development, organizations can implement real-time checks to ensure that the software aligns with the specified requirements and that the requirements accurately mirror the present state of the code.
    This is a sample API with various endpoints for user onboarding.
  termsOfService: http://swagger.io/terms/
  contact:
    email: foo@enviate.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
servers:
  - url: http://localhost/api/v1
tags:
  - name: notification
    description: API to send notifications
paths:
  /notification/email:
    post:
      summary: Send Email Notification
      description: Send an email notification to the specified email address.
      operationId: send_email_notification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailNotificationRequest'
      responses:
        '200':
          description: Success
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseMessage'
  
components:
  schemas:
    EmailNotificationRequest:
      type: object
      properties:
        email:
          type: string
          format: email
          description: Email address of the recipient.
        notification_text:
          type: string
          description: The text content of the email notification.
    
    ResponseMessage:
      type: object
      title: ResponseMessage
      properties:
        message:
          type: string
          description: ResponseMessage        