# generated by datamodel-codegen:
#   filename:  webhook.yaml
#   timestamp: 2023-08-11T11:50:39+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class ResponseMessage(BaseModel):
    message: Optional[str] = Field(None, description='ResponseMessage')
