"""Added revision column in user_resource_linkage table

Revision ID: 4c888d3b3fd7
Revises: c1cbccef81fb
Create Date: 2023-09-26 13:47:58.709212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c888d3b3fd7'
down_revision = 'c1cbccef81fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_resource_linkage', sa.Column('reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_resource_linkage', 'reason')
    # ### end Alembic commands ###
