# generated by datamodel-codegen:
#   filename:  human_inloop.yaml
#   timestamp: 2023-09-27T06:09:37+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field

from enum import Enum as ENUM

class CodeInfo(BaseModel):
    name: Optional[str] = Field(None, description='Name of the code.')
    contents: Optional[str] = Field(None, description='Content of the code.')
    file_path: Optional[str] = Field(
        None, description='Name of the file containing the code.'
    )


class RequirementInfo(BaseModel):
    title: Optional[str] = Field(None, description='Name of the requirement.')
    description: Optional[str] = Field(
        None, description='Description of the requirement.'
    )
    task_id: Optional[str] = Field(
        None, description='ID of the task associated with the requirement.'
    )


class TopLinkInfo(BaseModel):
    top_link_id: Optional[int] = Field(None, description='ID of the top link.')
    top_link_score: Optional[str] = Field(None, description='Score of the top link')
    code_info: Optional[CodeInfo] = None
    requirement_info: Optional[RequirementInfo] = None
    human_verification: Optional[str] = Field(
        None, description='user validation input'
    )


class VerificationInfo(BaseModel):
    top_link_id: Optional[int] = Field(None, description='ID of the top link.')
    human_verification: Optional[bool] = Field(
        None, description='Indicates whether the link was a pass or fail'
    )


class ValidateResponseMessage(BaseModel):
    message: Optional[str] = Field(None, description='Response message.')
    support_status: Optional[str] = Field(
        None, description='Status if the repo will be supported or not'
    )
    reason: Optional[str] = Field(
        None, description='Reason of why it is unsupported'
    )


class LinkageResponseMessage(BaseModel):
    message: Optional[str] = Field(None, description='Response message.')
    linkage_status: Optional[str] = Field(None, description='Linkage Status')


class LinkageStatusEnum(ENUM):
    NOT_STARTED = 'NOT_STARTED'
    INITIATED = 'INITIATED'
    FAILED = "FAILED"
    AWAITING_VALIDATION = 'AWAITING_VALIDATION'
    SUPPORTED = 'SUPPORTED'
    UNSUPPORTED = 'UNSUPPORTED'
    COMPLETED='COMPLETED'


class HumanVerification(ENUM):
    PASS = 'PASS'
    FAIL = 'FAIL'